const actions = {
  LOIKYTHUAT_GET_LIST_REQUEST: "LOIKYTHUAT_GET_LIST_REQUEST",
  LOIKYTHUAT_GET_LIST_REQUEST_SUCCESS: "LOIKYTHUAT_GET_LIST_REQUEST_SUCCESS",
  LOIKYTHUAT_GET_LIST_REQUEST_ERROR: "LOIKYTHUAT_GET_LIST_REQUEST_ERROR",
  getList: (filter) => ({
    type: actions.LOIKYTHUAT_GET_LIST_REQUEST,
    payload: { filter },
  }),
};

export default actions;
