const actions = {
  SYNCTHETIC_GET_INIT_REQUEST: "SYNCTHETIC_GET_INIT_REQUEST",
  SYNCTHETIC_GET_INIT_REQUEST_SUCCESS: "SYNCTHETIC_GET_INIT_REQUEST_SUCCESS",
  SYNCTHETIC_GET_INIT_REQUEST_ERROR: "SYNCTHETIC_GET_INIT_REQUEST_ERROR",
  getInit: (filterData) => ({
    type: actions.SYNCTHETIC_GET_INIT_REQUEST,
    payload: { filterData },
  }),

  SYNCTHETIC_GET_LIST_REQUEST: "SYNCTHETIC_GET_LIST_REQUEST",
  SYNCTHETIC_GET_LIST_REQUEST_SUCCESS: "SYNCTHETIC_GET_LIST_REQUEST_SUCCESS",
  SYNCTHETIC_GET_LIST_REQUEST_ERROR: "SYNCTHETIC_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.SYNCTHETIC_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
