const actions = {
  QUANLYDONTHUDONDOC_GET_INIT_REQUEST: 'QUANLYDONTHUDONDOC_GET_INIT_REQUEST',
  QUANLYDONTHUDONDOC_GET_INIT_REQUEST_SUCCESS:
    'QUANLYDONTHUDONDOC_GET_INIT_REQUEST_SUCCESS',
  QUANLYDONTHUDONDOC_GET_INIT_REQUEST_ERROR:
    'QUANLYDONTHUDONDOC_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.QUANLYDONTHUDONDOC_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  QUANLYDONTHUDONDOC_GET_LIST_REQUEST: 'QUANLYDONTHUDONDOC_GET_LIST_REQUEST',
  QUANLYDONTHUDONDOC_GET_LIST_REQUEST_SUCCESS:
    'QUANLYDONTHUDONDOC_GET_LIST_REQUEST_SUCCESS',
  QUANLYDONTHUDONDOC_GET_LIST_REQUEST_ERROR:
    'QUANLYDONTHUDONDOC_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.QUANLYDONTHUDONDOC_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
