const actions = {
  TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST:
    'TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST',
  TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST_SUCCESS:
    'TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST_SUCCESS',
  TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST_ERROR:
    'TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.TIEPCONGDANTHUONGXUYEN_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST:
    'TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST',
  TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST_SUCCESS:
    'TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST_SUCCESS',
  TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST_ERROR:
    'TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.TIEPCONGDANTHUONGXUYEN_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
