const actions = {
  GETDULIEUDAUKY_INIT_REQUEST: 'GETDULIEUDAUKY_INIT_REQUEST',
  GETDULIEUDAUKY_INIT_REQUEST_SUCCESS: 'GETDULIEUDAUKY_INIT_REQUEST_SUCCESS',
  GETDULIEUDAUKY_INIT_REQUEST_ERROR: 'GETDULIEUDAUKY_INIT_REQUEST_ERROR',
  GETCOQUANDULIEUDAUKY_INIT_REQUEST: 'GETCOQUANDULIEUDAUKY_INIT_REQUEST',
  GETCOQUANDULIEUDAUKY_INIT_REQUEST_SUCCESS:
    'GETCOQUANDULIEUDAUKY_INIT_REQUEST_SUCCESS',
  GETCOQUANDULIEUDAUKY_INIT_REQUEST_ERROR:
    'GETCOQUANDULIEUDAUKY_INIT_REQUEST_ERROR',

  CLEAR_DATA_BAOCAO: 'CLEAR_DATA_BAOCAO',
  getData: (filterData) => ({
    type: actions.GETDULIEUDAUKY_INIT_REQUEST,
    payload: {filterData},
  }),

  getCoQuan: (filterData) => ({
    type: actions.GETCOQUANDULIEUDAUKY_INIT_REQUEST,
    payload: {filterData},
  }),

  clearData: () => ({
    type: actions.CLEAR_DATA_BAOCAO,
  }),
};

export default actions;
