const actions = {
  THIHANH_GET_INIT_REQUEST: 'THIHANH_GET_INIT_REQUEST',
  THIHANH_GET_INIT_REQUEST_SUCCESS: 'THIHANH_GET_INIT_REQUEST_SUCCESS',
  THIHANH_GET_INIT_REQUEST_ERROR: 'THIHANH_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.THIHANH_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  THIHANH_GET_LIST_REQUEST: 'THIHANH_GET_LIST_REQUEST',
  THIHANH_GET_LIST_REQUEST_SUCCESS: 'THIHANH_GET_LIST_REQUEST_SUCCESS',
  THIHANH_GET_LIST_REQUEST_ERROR: 'THIHANH_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.THIHANH_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
