const actions = {
  QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST:
    'QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST',
  QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST_SUCCESS:
    'QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST_SUCCESS',
  QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST_ERROR:
    'QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.QUANLYDONTHUCANDONDOC_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST:
    'QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST',
  QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST_SUCCESS:
    'QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST_SUCCESS',
  QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST_ERROR:
    'QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.QUANLYDONTHUCANDONDOC_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
