const actions = {
  XULYDON_GET_INIT_REQUEST: 'XULYDON_GET_INIT_REQUEST',
  XULYDON_GET_INIT_REQUEST_SUCCESS: 'XULYDON_GET_INIT_REQUEST_SUCCESS',
  XULYDON_GET_INIT_REQUEST_ERROR: 'XULYDON_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.XULYDON_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  XULYDON_GET_LIST_REQUEST: 'XULYDON_GET_LIST_REQUEST',
  XULYDON_GET_LIST_REQUEST_SUCCESS: 'XULYDON_GET_LIST_REQUEST_SUCCESS',
  XULYDON_GET_LIST_REQUEST_ERROR: 'XULYDON_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.XULYDON_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
