const actions = {
  PHANXULYDON_GET_INIT_REQUEST: 'PHANXULYDON_GET_INIT_REQUEST',
  PHANXULYDON_GET_INIT_REQUEST_SUCCESS: 'PHANXULYDON_GET_INIT_REQUEST_SUCCESS',
  PHANXULYDON_GET_INIT_REQUEST_ERROR: 'PHANXULYDON_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.PHANXULYDON_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  PHANXULYDON_GET_LIST_REQUEST: 'PHANXULYDON_GET_LIST_REQUEST',
  PHANXULYDON_GET_LIST_REQUEST_SUCCESS: 'PHANXULYDON_GET_LIST_REQUEST_SUCCESS',
  PHANXULYDON_GET_LIST_REQUEST_ERROR: 'PHANXULYDON_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.PHANXULYDON_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
