const actions = {
  THEOGIOIGIAIQUYET_GET_INIT_REQUEST: 'THEOGIOIGIAIQUYET_GET_INIT_REQUEST',
  THEOGIOIGIAIQUYET_GET_INIT_REQUEST_SUCCESS:
    'THEOGIOIGIAIQUYET_GET_INIT_REQUEST_SUCCESS',
  THEOGIOIGIAIQUYET_GET_INIT_REQUEST_ERROR:
    'THEOGIOIGIAIQUYET_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.THEOGIOIGIAIQUYET_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  THEOGIOIGIAIQUYET_GET_LIST_REQUEST: 'THEOGIOIGIAIQUYET_GET_LIST_REQUEST',
  THEOGIOIGIAIQUYET_GET_LIST_REQUEST_SUCCESS:
    'THEOGIOIGIAIQUYET_GET_LIST_REQUEST_SUCCESS',
  THEOGIOIGIAIQUYET_GET_LIST_REQUEST_ERROR:
    'THEOGIOIGIAIQUYET_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.THEOGIOIGIAIQUYET_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
