const actions = {
  PHEDUYETKETQUAXULY_GET_INIT_REQUEST: 'PHEDUYETKETQUAXULY_GET_INIT_REQUEST',
  PHEDUYETKETQUAXULY_GET_INIT_REQUEST_SUCCESS:
    'PHEDUYETKETQUAXULY_GET_INIT_REQUEST_SUCCESS',
  PHEDUYETKETQUAXULY_GET_INIT_REQUEST_ERROR:
    'PHEDUYETKETQUAXULY_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.PHEDUYETKETQUAXULY_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  PHEDUYETKETQUAXULY_GET_LIST_REQUEST: 'PHEDUYETKETQUAXULY_GET_LIST_REQUEST',
  PHEDUYETKETQUAXULY_GET_LIST_REQUEST_SUCCESS:
    'PHEDUYETKETQUAXULY_GET_LIST_REQUEST_SUCCESS',
  PHEDUYETKETQUAXULY_GET_LIST_REQUEST_ERROR:
    'PHEDUYETKETQUAXULY_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.PHEDUYETKETQUAXULY_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
