const actions = {
  QLTRINHTUTHUTUC_GET_LIST_REQUEST: 'QLTRINHTUTHUTUC_GET_LIST_REQUEST',
  QLTRINHTUTHUTUC_GET_LIST_REQUEST_SUCCESS:
    'QLTRINHTUTHUTUC_GET_LIST_REQUEST_SUCCESS',
  QLTRINHTUTHUTUC_GET_LIST_REQUEST_ERROR:
    'QLTRINHTUTHUTUC_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.QLTRINHTUTHUTUC_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
