const actions = {
  BAOCAOCHUNG_INIT_REQUEST: 'BAOCAOCHUNG_INIT_REQUEST',
  BAOCAOCHUNG_INIT_REQUEST_SUCCESS: 'BAOCAOCHUNG_INIT_REQUEST_SUCCESS',
  BAOCAOCHUNG_INIT_REQUEST_ERROR: 'BAOCAOCHUNG_INIT_REQUEST_ERROR',
  BAOCAOCHUNGGET_INIT_REQUEST: 'BAOCAOCHUNGGET_INIT_REQUEST',
  BAOCAOCHUNGGET_INIT_REQUEST_SUCCESS: 'BAOCAOCHUNGGET_INIT_REQUEST_SUCCESS',
  BAOCAOCHUNGGET_INIT_REQUEST_ERROR: 'BAOCAOCHUNGGET_INIT_REQUEST_ERROR',

  CLEAR_DATA_BAOCAO: 'CLEAR_DATA_BAOCAO',
  getData: (filterData) => ({
    type: actions.BAOCAOCHUNG_INIT_REQUEST,
    payload: {filterData},
  }),

  getCoQuan: (filterData) => ({
    type: actions.BAOCAOCHUNGGET_INIT_REQUEST,
    payload: {filterData},
  }),

  clearData: () => ({
    type: actions.CLEAR_DATA_BAOCAO,
  }),
};

export default actions;
