const actions = {
  HOSODONTHU_GET_INIT_REQUEST: 'HOSODONTHU_GET_INIT_REQUEST',
  HOSODONTHU_GET_INIT_REQUEST_SUCCESS: 'HOSODONTHU_GET_INIT_REQUEST_SUCCESS',
  HOSODONTHU_GET_INIT_REQUEST_ERROR: 'HOSODONTHU_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.HOSODONTHU_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  HOSODONTHU_GET_LIST_REQUEST: 'HOSODONTHU_GET_LIST_REQUEST',
  HOSODONTHU_GET_LIST_REQUEST_SUCCESS: 'HOSODONTHU_GET_LIST_REQUEST_SUCCESS',
  HOSODONTHU_GET_LIST_REQUEST_ERROR: 'HOSODONTHU_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.HOSODONTHU_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
