const actions = {
  DONGBODULIEU_GET_INIT_REQUEST: 'DONGBODULIEU_GET_INIT_REQUEST',
  DONGBODULIEU_GET_INIT_REQUEST_SUCCESS:
    'DONGBODULIEU_GET_INIT_REQUEST_SUCCESS',
  DONGBODULIEU_GET_INIT_REQUEST_ERROR: 'DONGBODULIEU_GET_INIT_REQUEST_ERROR',
  getInit: (filterData) => ({
    type: actions.DONGBODULIEU_GET_INIT_REQUEST,
    payload: {filterData},
  }),

  DONGBODULIEU_GET_LIST_REQUEST: 'DONGBODULIEU_GET_LIST_REQUEST',
  DONGBODULIEU_GET_LIST_REQUEST_SUCCESS:
    'DONGBODULIEU_GET_LIST_REQUEST_SUCCESS',
  DONGBODULIEU_GET_LIST_REQUEST_ERROR: 'DONGBODULIEU_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.DONGBODULIEU_GET_LIST_REQUEST,
    payload: {filterData},
  }),

  DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST:
    'DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST',
  DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST_SUCCESS:
    'DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST_SUCCESS',
  DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST_ERROR:
    'DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST_ERROR',
  getDanhMucKNTCQuocGia: (filterData) => ({
    type: actions.DONGBODULIEU_GET_DANHMUCKNTCQUOCGIA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
