const actions = {
  CAPNHATQDGIAIQUYET_GET_INIT_REQUEST: 'CAPNHATQDGIAIQUYET_GET_INIT_REQUEST',
  CAPNHATQDGIAIQUYET_GET_INIT_REQUEST_SUCCESS:
    'CAPNHATQDGIAIQUYET_GET_INIT_REQUEST_SUCCESS',
  CAPNHATQDGIAIQUYET_GET_INIT_REQUEST_ERROR:
    'CAPNHATQDGIAIQUYET_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.CAPNHATQDGIAIQUYET_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  CAPNHATQDGIAIQUYET_GET_LIST_REQUEST: 'CAPNHATQDGIAIQUYET_GET_LIST_REQUEST',
  CAPNHATQDGIAIQUYET_GET_LIST_REQUEST_SUCCESS:
    'CAPNHATQDGIAIQUYET_GET_LIST_REQUEST_SUCCESS',
  CAPNHATQDGIAIQUYET_GET_LIST_REQUEST_ERROR:
    'CAPNHATQDGIAIQUYET_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.CAPNHATQDGIAIQUYET_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
