const actions = {
  CAPNHATGDGIAOXACMINH_INIT_REQUEST: 'CAPNHATGDGIAOXACMINH_INIT_REQUEST',
  CAPNHATGDGIAOXACMINH_INIT_REQUEST_SUCCESS:
    'CAPNHATGDGIAOXACMINH_INIT_REQUEST_SUCCESS',
  CAPNHATGDGIAOXACMINH_INIT_REQUEST_ERROR:
    'CAPNHATGDGIAOXACMINH_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.CAPNHATGDGIAOXACMINH_INIT_REQUEST,
    payload: {filterData},
  }),
  CAPNHATGDGIAOXACMINH_LIST_REQUEST: 'CAPNHATGDGIAOXACMINH_LIST_REQUEST',
  CAPNHATGDGIAOXACMINH_LIST_REQUEST_SUCCESS:
    'CAPNHATGDGIAOXACMINH_LIST_REQUEST_SUCCESS',
  CAPNHATGDGIAOXACMINH_LIST_REQUEST_ERROR:
    'CAPNHATGDGIAOXACMINH_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.CAPNHATGDGIAOXACMINH_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
