const actions = {
  CAPNHATSOTHEODOI_GET_INIT_REQUEST: "CAPNHATSOTHEODOI_GET_INIT_REQUEST",
  CAPNHATSOTHEODOI_GET_INIT_REQUEST_SUCCESS: "CAPNHATSOTHEODOI_GET_INIT_REQUEST_SUCCESS",
  CAPNHATSOTHEODOI_GET_INIT_REQUEST_ERROR: "CAPNHATSOTHEODOI_GET_INIT_REQUEST_ERROR",
  getInit: (filterData) => ({
    type: actions.CAPNHATSOTHEODOI_GET_INIT_REQUEST,
    payload: { filterData },
  }),

  CAPNHATSOTHEODOI_GET_LIST_REQUEST: "CAPNHATSOTHEODOI_GET_LIST_REQUEST",
  CAPNHATSOTHEODOI_GET_LIST_REQUEST_SUCCESS: "CAPNHATSOTHEODOI_GET_LIST_REQUEST_SUCCESS",
  CAPNHATSOTHEODOI_GET_LIST_REQUEST_ERROR: "CAPNHATSOTHEODOI_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.CAPNHATSOTHEODOI_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
