const actions = {
  QUYETDINHGIAIQUYET_GET_LIST_REQUEST: 'QUYETDINHGIAIQUYET_GET_LIST_REQUEST',
  QUYETDINHGIAIQUYET_GET_LIST_REQUEST_SUCCESS:
    'QUYETDINHGIAIQUYET_GET_LIST_REQUEST_SUCCESS',
  QUYETDINHGIAIQUYET_GET_LIST_REQUEST_ERROR:
    'QUYETDINHGIAIQUYET_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.QUYETDINHGIAIQUYET_GET_LIST_REQUEST,
    payload: {filterData},
  }),
  QUYETDINHGIAIQUYET_GET_INIT_REQUEST: 'QUYETDINHGIAIQUYET_GET_INIT_REQUEST',
  QUYETDINHGIAIQUYET_GET_INIT_REQUEST_SUCCESS:
    'QUYETDINHGIAIQUYET_GET_INIT_REQUEST_SUCCESS',
  QUYETDINHGIAIQUYET_GET_INIT_REQUEST_ERROR:
    'QUYETDINHGIAIQUYET_GET_INIT_REQUEST_ERROR',
  getInit: (filterData) => ({
    type: actions.QUYETDINHGIAIQUYET_GET_INIT_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
