const actions = {
  GIAIQUYETDONTHU_GET_INIT_REQUEST: 'GIAIQUYETDONTHU_GET_INIT_REQUEST',
  GIAIQUYETDONTHU_GET_INIT_REQUEST_SUCCESS:
    'GIAIQUYETDONTHU_GET_INIT_REQUEST_SUCCESS',
  GIAIQUYETDONTHU_GET_INIT_REQUEST_ERROR:
    'GIAIQUYETDONTHU_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.GIAIQUYETDONTHU_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  GIAIQUYETDONTHU_GET_LIST_REQUEST: 'GIAIQUYETDONTHU_GET_LIST_REQUEST',
  GIAIQUYETDONTHU_GET_LIST_REQUEST_SUCCESS:
    'GIAIQUYETDONTHU_GET_LIST_REQUEST_SUCCESS',
  GIAIQUYETDONTHU_GET_LIST_REQUEST_ERROR:
    'GIAIQUYETDONTHU_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.GIAIQUYETDONTHU_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
