const actions = {
  CAPNHATSOLIEU_GET_INIT_REQUEST: "CAPNHATSOLIEU_GET_INIT_REQUEST",
  CAPNHATSOLIEU_GET_INIT_REQUEST_SUCCESS: "CAPNHATSOLIEU_GET_INIT_REQUEST_SUCCESS",
  CAPNHATSOLIEU_GET_INIT_REQUEST_ERROR: "CAPNHATSOLIEU_GET_INIT_REQUEST_ERROR",
  getInit: (filterData) => ({
    type: actions.CAPNHATSOLIEU_GET_INIT_REQUEST,
    payload: { filterData },
  }),

  CAPNHATSOLIEU_GET_LIST_REQUEST: "CAPNHATSOLIEU_GET_LIST_REQUEST",
  CAPNHATSOLIEU_GET_LIST_REQUEST_SUCCESS: "CAPNHATSOLIEU_GET_LIST_REQUEST_SUCCESS",
  CAPNHATSOLIEU_GET_LIST_REQUEST_ERROR: "CAPNHATSOLIEU_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.CAPNHATSOLIEU_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
