const actions = {
  SOTIEPDAN_GET_INIT_REQUEST: 'SOTIEPDAN_GET_INIT_REQUEST',
  SOTIEPDAN_GET_INIT_REQUEST_SUCCESS: 'SOTIEPDAN_GET_INIT_REQUEST_SUCCESS',
  SOTIEPDAN_GET_INIT_REQUEST_ERROR: 'SOTIEPDAN_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.SOTIEPDAN_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  SOTIEPDAN_GET_LIST_REQUEST: 'SOTIEPDAN_GET_LIST_REQUEST',
  SOTIEPDAN_GET_LIST_REQUEST_SUCCESS: 'SOTIEPDAN_GET_LIST_REQUEST_SUCCESS',
  SOTIEPDAN_GET_LIST_REQUEST_ERROR: 'SOTIEPDAN_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.SOTIEPDAN_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
