const actions = {
  QLLICHTIEPDAN_GET_LIST_REQUEST: 'QLLICHTIEPDAN_GET_LIST_REQUEST',
  QLLICHTIEPDAN_GET_LIST_REQUEST_SUCCESS:
    'QLLICHTIEPDAN_GET_LIST_REQUEST_SUCCESS',
  QLLICHTIEPDAN_GET_LIST_REQUEST_ERROR: 'QLLICHTIEPDAN_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.QLLICHTIEPDAN_GET_LIST_REQUEST,
    payload: {filterData},
  }),
  QLLICHTIEPDAN_GET_INIT_REQUEST: 'QLLICHTIEPDAN_GET_INIT_REQUEST',
  QLLICHTIEPDAN_GET_INIT_REQUEST_SUCCESS:
    'QLLICHTIEPDAN_GET_INIT_REQUEST_SUCCESS',
  QLLICHTIEPDAN_GET_INIT_REQUEST_ERROR: 'QLLICHTIEPDAN_GET_INIT_REQUEST_ERROR',
  getInit: (filterData) => ({
    type: actions.QLLICHTIEPDAN_GET_INIT_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
