const actions = {
  QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST: 'QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST',
  QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST_SUCCESS:
    'QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST_SUCCESS',
  QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST_ERROR:
    'QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.QUANLYVUVIECPHUCTAP_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST: 'QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST',
  QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST_SUCCESS:
    'QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST_SUCCESS',
  QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST_ERROR:
    'QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.QUANLYVUVIECPHUCTAP_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
