const actions = {
  QDTHIHANH_GET_INIT_REQUEST: 'QDTHIHANH_GET_INIT_REQUEST',
  QDTHIHANH_GET_INIT_REQUEST_SUCCESS: 'QDTHIHANH_GET_INIT_REQUEST_SUCCESS',
  QDTHIHANH_GET_INIT_REQUEST_ERROR: 'QDTHIHANH_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.QDTHIHANH_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  QDTHIHANH_GET_LIST_REQUEST: 'QDTHIHANH_GET_LIST_REQUEST',
  QDTHIHANH_GET_LIST_REQUEST_SUCCESS: 'QDTHIHANH_GET_LIST_REQUEST_SUCCESS',
  QDTHIHANH_GET_LIST_REQUEST_ERROR: 'QDTHIHANH_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.QDTHIHANH_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
