const actions = {
  NHAPLIEUPHANMEM_INIT_REQUEST: 'NHAPLIEUPHANMEM_INIT_REQUEST',
  NHAPLIEUPHANMEM_INIT_REQUEST_SUCCESS: 'NHAPLIEUPHANMEM_INIT_REQUEST_SUCCESS',
  NHAPLIEUPHANMEM_INIT_REQUEST_ERROR: 'NHAPLIEUPHANMEM_INIT_REQUEST_ERROR',
  GETCOQUANNHAPLIEU_INIT_REQUEST: 'GETCOQUANNHAPLIEU_INIT_REQUEST',
  GETCOQUANNHAPLIEU_INIT_REQUEST_SUCCESS:
    'GETCOQUANNHAPLIEU_INIT_REQUEST_SUCCESS',
  GETCOQUANNHAPLIEU_INIT_REQUEST_ERROR: 'GETCOQUANNHAPLIEU_INIT_REQUEST_ERROR',

  CLEAR_DATA_BAOCAO: 'CLEAR_DATA_BAOCAO',
  getData: (filterData) => ({
    type: actions.NHAPLIEUPHANMEM_INIT_REQUEST,
    payload: {filterData},
  }),

  getCoQuan: (filterData) => ({
    type: actions.GETCOQUANNHAPLIEU_INIT_REQUEST,
    payload: {filterData},
  }),

  clearData: () => ({
    type: actions.CLEAR_DATA_BAOCAO,
  }),
};

export default actions;
