const actions = {
  PHANXULYDONCT_GET_INIT_REQUEST: 'PHANXULYDONCT_GET_INIT_REQUEST',
  PHANXULYDONCT_GET_INIT_REQUEST_SUCCESS:
    'PHANXULYDONCT_GET_INIT_REQUEST_SUCCESS',
  PHANXULYDONCT_GET_INIT_REQUEST_ERROR:
    'PHANXULYDONCT_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.PHANXULYDONCT_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  PHANXULYDONCT_GET_LIST_REQUEST: 'PHANXULYDONCT_GET_LIST_REQUEST',
  PHANXULYDONCT_GET_LIST_REQUEST_SUCCESS:
    'PHANXULYDONCT_GET_LIST_REQUEST_SUCCESS',
  PHANXULYDONCT_GET_LIST_REQUEST_ERROR:
    'PHANXULYDONCT_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.PHANXULYDONCT_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
