const actions = {
  DONTHUDATIEPNHAN_GET_INIT_REQUEST: 'DONTHUDATIEPNHAN_GET_INIT_REQUEST',
  DONTHUDATIEPNHAN_GET_INIT_REQUEST_SUCCESS:
    'DONTHUDATIEPNHAN_GET_INIT_REQUEST_SUCCESS',
  DONTHUDATIEPNHAN_GET_INIT_REQUEST_ERROR:
    'DONTHUDATIEPNHAN_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.DONTHUDATIEPNHAN_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  DONTHUDATIEPNHAN_GET_LIST_REQUEST: 'DONTHUDATIEPNHAN_GET_LIST_REQUEST',
  DONTHUDATIEPNHAN_GET_LIST_REQUEST_SUCCESS:
    'DONTHUDATIEPNHAN_GET_LIST_REQUEST_SUCCESS',
  DONTHUDATIEPNHAN_GET_LIST_REQUEST_ERROR:
    'DONTHUDATIEPNHAN_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.DONTHUDATIEPNHAN_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
