const actions = {
  INSPECTION_GET_INIT_REQUEST: 'INSPECTION_GET_INIT_REQUEST',
  INSPECTION_GET_INIT_REQUEST_SUCCESS: 'INSPECTION_GET_INIT_REQUEST_SUCCESS',
  INSPECTION_GET_INIT_REQUEST_ERROR: 'INSPECTION_GET_INIT_REQUEST_ERROR',
  getInit: (filterData) => ({
    type: actions.INSPECTION_GET_INIT_REQUEST,
    payload: {filterData},
  }),

  INSPECTION_GET_LIST_REQUEST: 'INSPECTION_GET_LIST_REQUEST',
  INSPECTION_GET_LIST_REQUEST_SUCCESS: 'INSPECTION_GET_LIST_REQUEST_SUCCESS',
  INSPECTION_GET_LIST_REQUEST_ERROR: 'INSPECTION_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.INSPECTION_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
