const actions = {
  REPORTDOCUMENT_GET_INIT_REQUEST: "REPORTDOCUMENT_GET_INIT_REQUEST",
  REPORTDOCUMENT_GET_INIT_REQUEST_SUCCESS:
    "REPORTDOCUMENT_GET_INIT_REQUEST_SUCCESS",
  REPORTDOCUMENT_GET_INIT_REQUEST_ERROR:
    "REPORTDOCUMENT_GET_INIT_REQUEST_ERROR",
  getInit: (filterData) => ({
    type: actions.REPORTDOCUMENT_GET_INIT_REQUEST,
    payload: { filterData },
  }),

  REPORTDOCUMENT_GET_LIST_REQUEST: "REPORTDOCUMENT_GET_LIST_REQUEST",
  REPORTDOCUMENT_GET_LIST_REQUEST_SUCCESS:
    "REPORTDOCUMENT_GET_LIST_REQUEST_SUCCESS",
  REPORTDOCUMENT_GET_LIST_REQUEST_ERROR:
    "REPORTDOCUMENT_GET_LIST_REQUEST_ERROR",
  getList: (filterData) => ({
    type: actions.REPORTDOCUMENT_GET_LIST_REQUEST,
    payload: { filterData },
  }),
};

export default actions;
