const actions = {
  GIAOXACMINH_GET_INIT_REQUEST: 'GIAOXACMINH_GET_INIT_REQUEST',
  GIAOXACMINH_GET_INIT_REQUEST_SUCCESS: 'GIAOXACMINH_GET_INIT_REQUEST_SUCCESS',
  GIAOXACMINH_GET_INIT_REQUEST_ERROR: 'GIAOXACMINH_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.GIAOXACMINH_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  GIAOXACMINH_GET_LIST_REQUEST: 'GIAOXACMINH_GET_LIST_REQUEST',
  GIAOXACMINH_GET_LIST_REQUEST_SUCCESS: 'GIAOXACMINH_GET_LIST_REQUEST_SUCCESS',
  GIAOXACMINH_GET_LIST_REQUEST_ERROR: 'GIAOXACMINH_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.GIAOXACMINH_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
