const actions = {
  QUANLYEMAIL_GET_LIST_REQUEST: 'QUANLYEMAIL_GET_LIST_REQUEST',
  QUANLYEMAIL_GET_LIST_REQUEST_SUCCESS: 'QUANLYEMAIL_GET_LIST_REQUEST_SUCCESS',
  QUANLYEMAIL_GET_LIST_REQUEST_ERROR: 'QUANLYEMAIL_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.QUANLYEMAIL_GET_LIST_REQUEST,
    payload: {filterData},
  }),
  QUANLYEMAIL_GET_INIT_REQUEST: 'QUANLYEMAIL_GET_INIT_REQUEST',
  QUANLYEMAIL_GET_INIT_REQUEST_SUCCESS: 'QUANLYEMAIL_GET_INIT_REQUEST_SUCCESS',
  QUANLYEMAIL_GET_INIT_REQUEST_ERROR: 'QUANLYEMAIL_GET_INIT_REQUEST_ERROR',
  getInit: (filterData) => ({
    type: actions.QUANLYEMAIL_GET_INIT_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
