const actions = {
  TIEPNHANDON_GET_INIT_REQUEST: 'TIEPNHANDON_GET_INIT_REQUEST',
  TIEPNHANDON_GET_INIT_REQUEST_SUCCESS: 'TIEPNHANDON_GET_INIT_REQUEST_SUCCESS',
  TIEPNHANDON_GET_INIT_REQUEST_ERROR: 'TIEPNHANDON_GET_INIT_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.TIEPNHANDON_GET_INIT_REQUEST,
    payload: {filterData},
  }),
  TIEPNHANDON_GET_LIST_REQUEST: 'TIEPNHANDON_GET_LIST_REQUEST',
  TIEPNHANDON_GET_LIST_REQUEST_SUCCESS: 'TIEPNHANDON_GET_LIST_REQUEST_SUCCESS',
  TIEPNHANDON_GET_LIST_REQUEST_ERROR: 'TIEPNHANDON_GET_LIST_REQUEST_ERROR',
  getInitData: (filterData) => ({
    type: actions.TIEPNHANDON_GET_LIST_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
